[k8s-gen] Generate Kong Config
TempleEight/temple pull request #131
Opened 2020-03-16 16:35 UTC by Lewiky

Generate a kong config script (a series of curl requests to the kong admin endpoint to add routes to services)

2020-03-16 18:01 UTC, jaylees14 approved these changes
LGTM, just a few comments.

Wonder if `kube` is the right place for this tho? I know there's some Kube specific stuff in here, but if we do manage to do `DockerCompose` it would be mostly the same

2020-03-16 18:01 UTC, jaylees14 commented on src/main/scala/temple/generate/kube/KongConfigGenerator.scala
> +      "curl -i -X POST",
Can probably drop the `-i`
```suggestion
      "curl -X POST",
```

2020-03-16 18:01 UTC, jaylees14 commented on src/main/scala/temple/generate/kube/KongConfigGenerator.scala
> +      "curl -i -X POST",
Same here
```suggestion
      "curl -X POST",
```

2020-03-16 18:01 UTC, jaylees14 commented on src/main/scala/temple/generate/kube/KubernetesGenerator.scala
> +    (kubeFiles + kongConfig) ++ kongFiles
I likey

2020-03-17 12:37 UTC, c-harding requested changes
Happy to accept if you don’t agree

2020-03-17 12:37 UTC, xsanda commented on src/main/scala/temple/generate/kube/KongConfigGenerator.scala
> +    mkCode.escapedList(
Can `escapedList` use `\\\n  ` as the separator, so there’s no need for `indent`?

2020-03-17 12:37 UTC, xsanda commented on src/main/scala/temple/generate/kube/KongConfigGenerator.scala
> +    val urls = service.ports map {
Personally I think `service.ports.values map {port => ???}` would be a bit nicer, but up to you

2020-03-17 12:37 UTC, xsanda commented on src/main/scala/temple/generate/kube/KongConfigGenerator.scala
> +      indent("--data \"hosts[]=$KONG_ENTRY\""),
Should we triple-quote this? Would say consistency but all the others are s-strings anyway

2020-03-17 12:37 UTC, xsanda commented on src/main/scala/temple/generate/kube/KongConfigGenerator.scala
> +      this.shebang,
this use of `this` does seem unnecessary. We don’t use it for things like `generateServiceDef`

2020-03-17 12:37 UTC, xsanda commented on src/test/scala/temple/generate/kube/KongConfigGeneratorTest.scala
> +    output._2 should be(UnitTestData.userKongConfig)
Can we destructure the output of `KongConfigGenerator.generate` (`val (outputFileName, outputContents)`), instead of using tuple indexing (`._1`)?

2020-03-17 13:16 UTC, c-harding approved these changes
![](https://media.giphy.com/media/KRG6XGnCYB0L6/giphy.gif)

2020-03-17 14:52 UTC, merged